In [22]:
import pandas as pd
import geonamescache

gc = geonamescache.GeonamesCache()

In [67]:
df = pd.read_csv("D1.csv")
df[:10]

                                    headline countries         cities
0                 Zika Outbreak Hits Miami\n       NaN          Miami
1          Could Zika Reach New York City?\n       NaN  New York City
2          First Case  Zika in Miami Beach\n       NaN          Miami
3  Mystery Virus Spreads in Recife, Brazil\n    Brazil         Recife
4    Dallas man comes down with case  Zika\n       NaN         Dallas
5        Trinidad confirms first Zika case\n       NaN       Trinidad
6   Zika Concerns are Spreading in Houston\n       NaN        Houston
7    Geneve Scientists Battle to Find Cure\n       NaN            NaN
8    The CDC in Atlanta is Growing Worried\n       NaN        Atlanta
9       Zika Infested Monkeys in Sao Paulo\n       NaN            NaN

In [57]:
def get_loc_data(row):
    ret = {"latitude": None,
          "longitude": None,
          "countrycode": None}
    data = gc.get_cities_by_name(row["cities"])
    if data:
        
        data = list(data[0].values())[0]
        
        ret["latitude"] = data["latitude"]
        ret["longitude"] = data["longitude"]
        ret["countrycode"] = data["countrycode"]
    
    return ret

loc_data_dict = df.iloc[:10,:].apply(get_loc_data,axis=1)
#df["location"].unique().size

In [65]:
loc_df = pd.DataFrame(loc_data_dict.to_list())

In [92]:
full_df = pd.concat((df,loc_df),axis=1).drop("countries",axis=1)
full_df.to_csv("D2.csv",index=False)

In [93]:
full_df

,headline,cities,latitude,longitude,countrycode
0,Zika Outbreak Hits Miami\n,Miami,25.77427,-80.19366,US
1,Could Zika Reach New York City?\n,New York City,40.71427,-74.00597,US
2,First Case Zika in Miami Beach\n,Miami,25.77427,-80.19366,US
3,"Mystery Virus Spreads in Recife, Brazil\n",Recife,-8.05389,-34.88111,BR
4,Dallas man comes down with case Zika\n,Dallas,32.78306,-96.80667,US
5,Trinidad confirms first Zika case\n,Trinidad,-14.83333,-64.90000,BO
6,Zika Concerns are Spreading in Houston\n,Houston,29.76328,-95.36327,US
7,Geneve Scientists Battle to Find Cure\n,NaN,NaN,NaN,None
8,The CDC in Atlanta is Growing Worried\n,Atlanta,33.74900,-84.38798,US
9,Zika Infested Monkeys in Sao Paulo\n,NaN,NaN,NaN,None
10,Brownsville teen contracts Zika virus\n,Brownsville,NaN,NaN,NaN
11,Mosquito control efforts in St. Louis take new...,St. Louis,NaN,NaN,NaN
12,San Juan reports 1st U.S. Zika-related death a...,San Juan,NaN,NaN,NaN
13,"Flu outbreak in Galveston, Texas\n",Galveston,NaN,NaN,NaN
14,Zika alert – Manila now threatened\n,Manila,NaN,NaN,NaN
15,Zika afflicts 7 in Iloilo City\n,Iloilo,NaN,NaN,NaN
16,New Los Angeles Hairstyle goes Viral\n,Los Angeles,NaN,NaN,NaN
17,Louisiana Zika cases up to 26\n,NaN,NaN,NaN,NaN
18,Orlando volunteers aid Zika research\n,Orlando,NaN,NaN,NaN
19,Zika infects pregnant woman in Cebu\n,NaN,NaN,NaN,NaN
20,Chicago's First Zika Case Confirmed\n,Chicago,NaN,NaN,NaN
21,Tampa Bay Area Zika Case Count Climbs\n,Tampa,NaN,NaN,NaN
22,"Bad Water Leads to Sickness in Flint, Michigan\n",Flint,NaN,NaN,NaN
23,Baltimore plans for Zika virus\n,Baltimore,NaN,NaN,NaN
24,London Health Unit Tracks Mad Cow Disease\n,London,NaN,NaN,NaN
25,Zika cases in Vietnam's Ho Chi Minh City surge\n,Ho,NaN,NaN,NaN
26,Philadelphia experts track pandemic\n,Philadelphia,NaN,NaN,NaN
27,Flu season hits Boston\n,Boston,NaN,NaN,NaN
28,Scientists in Paris to look for answers\n,Paris,NaN,NaN,NaN
29,Key Zika Findings in San Diego Institute\n,San Diego,NaN,NaN,NaN
...,...,...,...,...,...
620,How to Avoid Chikungunya in Hampton\n,Hampton,NaN,NaN,NaN
621,Zika Reported in Sao Jose\n,NaN,NaN,NaN,NaN
622,Case Norovirus Reported in Stratford\n,Stratford,NaN,NaN,NaN
623,How to Avoid Hepatitis E in South Bend\n,South Bend,NaN,NaN,NaN
624,Hepatitis C Outbreak in Bethlehem\n,Bethlehem,NaN,NaN,NaN
625,Davenport is infested with Dengue\n,Davenport,NaN,NaN,NaN
626,Rumors about Swine Flu spreading in Suzhou hav...,Suzhou,NaN,NaN,NaN
627,Malaria Vaccine is now Required in Elyria\n,Elyria,NaN,NaN,NaN
628,Zika case reported in Antioquia\n,NaN,NaN,NaN,NaN
629,Case Swine Flu Reported in Tbilisi\n,Tbilisi,NaN,NaN,NaN
630,Chikungunya has not Left Pismo Beach\n,NaN,NaN,NaN,NaN
631,Zika spreads to La Joya\n,NaN,NaN,NaN,NaN
632,Influenza Keeps Spreading in Suffolk\n,Suffolk,NaN,NaN,NaN
633,More people in Allentown are infected with Chl...,Allentown,NaN,NaN,NaN
634,Mad Cow Disease re-emerges in Bedford\n,Bedford,NaN,NaN,NaN
635,Authorities are Worried about Spread Hepatit...,Yiwu,NaN,NaN,NaN
636,Zika Outbreak in Yurimaguas\n,Yurimaguas,NaN,NaN,NaN
637,Dengue Outbreak in Easton\n,Easton,NaN,NaN,NaN
638,Varicella has Arrived in Milton\n,Milton,NaN,NaN,NaN
639,New medicine wipes out Meningitis in Sevilla\n,Sevilla,NaN,NaN,NaN
640,Authorities are Worried about Spread Varicel...,Clovis,NaN,NaN,NaN
641,More Zika patients reported in Fort Worth\n,Fort Worth,NaN,NaN,NaN
642,Zika symptoms spotted in Boynton Beach\n,Boynton Beach,NaN,NaN,NaN
643,Outbreak Zika in Portoviejo\n,Portoviejo,NaN,NaN,NaN
644,Influenza Exposure in Muscat\n,Muscat,NaN,NaN,NaN
645,Rumors about Rabies spreading in Jerusalem hav...,Jerusalem,NaN,NaN,NaN
646,More Zika patients reported in Indang\n,Indang,NaN,NaN,NaN
647,Suva authorities confirmed spread Rotavirus\n,Suva,NaN,NaN,NaN
648,More Zika patients reported in Bella Vista\n,Bella Vista,NaN,NaN,NaN
649,Zika Outbreak in Wichita Falls\n,Wichita,NaN,NaN,NaN